name: CI Dev

on:
  push

env:
  VERSION: v0.2.0
  REPO: vcr.vngcloud.vn/60108-annd2-ingress

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Log in to the GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the vCR
        uses: docker/login-action@v3
        with:
          registry: vcr.vngcloud.vn
          username: ${{ secrets.VCR_USER }}
          password: ${{ secrets.VCR_PASSWORD }}

      - name: Build and push Docker image
        env:
          TARGET: vngcloud-ingress-controller
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
          platforms: linux/amd64
          outputs: type=registry
          tags: |
            ghcr.io/vngcloud/vngcloud-ingress-controller:${{ github.sha }}
            ${{ env.REPO }}/vngcloud-ingress-controller:${{ github.sha }}
            ${{ env.REPO }}/vngcloud-ingress-controller:${{ env.VERSION }}
          target: vngcloud-ingress-controller
      
      - name: Build and push Docker image
        env:
          TARGET: vngcloud-controller-manager
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
          platforms: linux/amd64
          outputs: type=registry
          tags: |
            ghcr.io/vngcloud/vngcloud-controller-manager:${{ github.sha }}
            ${{ env.REPO }}/vngcloud-controller-manager:${{ github.sha }}
            ${{ env.REPO }}/vngcloud-controller-manager:${{ env.VERSION }}
          target: vngcloud-controller-manager
      
      - name: Build and push Docker image
        env:
          TARGET: vngcloud-cm-webhook
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
          platforms: linux/amd64
          outputs: type=registry
          tags: |
            ghcr.io/vngcloud/vngcloud-cm-webhook:${{ github.sha }}
            ${{ env.REPO }}/vngcloud-cm-webhook:${{ github.sha }}
            ${{ env.REPO }}/vngcloud-cm-webhook:${{ env.VERSION }}
          target: vngcloud-cm-webhook
      
      - name: Build and push Docker image
        env:
          TARGET: vngcloud-ic-webhook
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
          platforms: linux/amd64
          outputs: type=registry
          tags: |
            ghcr.io/vngcloud/vngcloud-ic-webhook:${{ github.sha }}
            ${{ env.REPO }}/vngcloud-ic-webhook:${{ github.sha }}
            ${{ env.REPO }}/vngcloud-ic-webhook:${{ env.VERSION }}
          target: vngcloud-ic-webhook
