# go run github.com/golangci/golangci-lint/cmd/golangci-lint@v1.54.2 run ./...
# golangci-lint run ./...
---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches: ["dev", "main"]

###############
# Set the Job #
###############
permissions: {}

jobs:
  build:
    # Name the Job
    permissions:
      contents: read # to fetch code (actions/checkout)
      statuses: write # to mark status of each linter run (github/super-linter)

    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4.1.1
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter@v6.3.0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: dev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: "."
          # MARKDOWN_CONFIG_FILE: .markdownlint.yml
          VALIDATE_MARKDOWN: true
          VALIDATE_BASH: true
